apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rag-oct24-4
  janus-idp.io/tekton: rag-oct24-4
  backstage.io/kubernetes-id: rag-oct24-4
  backstage.io/kubernetes-namespace: mjf 
  app.kubernetes.io/part-of: rag-oct24-4
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- deployment-database.yaml
- service-database.yaml
- database-config.yaml
- rhoai/
