---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: rag-oct24-4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-oct24-4 
  name: rag-oct24-4
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi